import type { Metadata } from "next";
import { CallToAction, InnerHero, PageShell } from "../components";

export const metadata: Metadata = { title: "About Us | Gate Repairs Pretoria", description: "Meet the local technicians behind Gate Repairs Pretoria and learn how we deliver dependable gate automation and security services." };

const values = [
  ["01", "Innovation", "We keep pace with new security and home-automation products so clients benefit from practical, current technology."],
  ["02", "Expertise", "Continuous training gives our technicians broad hands-on knowledge across automation and security systems."],
  ["03", "Collaboration", "Strong supplier relationships help us source dependable equipment, spares and product support."],
  ["04", "Clear advice", "We explain the fault, the available options and the price before work begins."],
];

export default function AboutPage() {
  return <PageShell>
    <InnerHero eyebrow="About us" title="Local expertise. Honest service." copy="We help Pretoria homeowners and businesses keep their entrances and security systems working properly—with practical advice, responsive support and workmanship built to last." image="/images/electric-fence.webp" alt="Security installation at a Pretoria property" />
    <section className="section story-section"><div className="shell story-grid"><div><p className="eyebrow">Our story</p><h2>Built to make security service better.</h2></div><div className="story-copy"><p>Our journey began in 2017 with a clear vision: to provide dependable security and automation solutions for homes and businesses. Since then, we have served property owners across Pretoria with repairs, installations and ongoing support.</p><p>We have grown through continuous technician training, better products and strong working relationships with some of the security industry’s largest suppliers. That gives our clients informed recommendations and access to trusted equipment at fair prices.</p><p>Our first job is always to understand the actual fault. We assess before recommending, keep common parts close at hand and only suggest replacement when continued repair no longer makes financial sense.</p></div></div></section>
    <section className="about-proof"><div className="shell proof-grid"><div><strong>2017</strong><span>year established</span></div><div><strong>800+</strong><span>projects completed</span></div><div><strong>98%</strong><span>client satisfaction</span></div><div><strong>8+ years</strong><span>industry experience</span></div></div></section>
    <section className="section values-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">What guides us</p><h2>Built around your peace of mind.</h2></div><p>Every repair or installation should leave you with a safer property and a clear understanding of the work completed.</p></div><div className="value-grid">{values.map(([number,title,copy]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
    <section className="section process"><div className="shell process-grid"><div className="process-intro"><p className="eyebrow light">Why choose us</p><h2>The right fix, not the quickest sale.</h2><p>We work on all major brands and keep a practical stock of common parts. When repair is viable, we repair. When replacement makes more sense, we explain why.</p><a className="button button-orange" href="/services">Explore our services <span>→</span></a></div><ol className="steps"><li><span>01</span><div><h3>Experienced technicians</h3><p>Hands-on knowledge across gate motors and integrated security systems.</p></div></li><li><span>02</span><div><h3>Fast local response</h3><p>Pretoria-wide coverage with same-day support available.</p></div></li><li><span>03</span><div><h3>Work you can rely on</h3><p>Careful testing, service guarantees and support after installation.</p></div></li></ol></div></section>
    <section className="section testimonial-section"><div className="shell testimonial-card"><div className="stars">★★★★★</div><blockquote>“Exceptional service! This company goes above and beyond to meet their customers’ needs. I couldn’t be happier with the results.”</blockquote><p><strong>Kobus</strong><span>Faerie Glen, Pretoria</span></p></div></section>
    <section className="section gallery-section"><div className="shell"><div className="section-heading"><div><p className="eyebrow">Recent work</p><h2>Practical work. Neat results.</h2></div><p>A selection of the systems we repair and install for residential and business clients.</p></div><div className="about-gallery"><figure><img src="/images/garage-door.webp" alt="New sectional garage door installation" /><figcaption>Sectional garage doors</figcaption></figure><figure><img src="/images/electric-fence.webp" alt="Multi-line electric fence installation" /><figcaption>Electric fencing</figcaption></figure><figure><img src="/images/gate-motor.webp" alt="Gate motor repair" /><figcaption>Gate automation</figcaption></figure><figure><img src="/images/cctv.webp" alt="Security camera installation" /><figcaption>CCTV systems</figcaption></figure></div></div></section>
    <CallToAction title="Put a dependable team on the job." />
  </PageShell>;
}
